#!/bin/sh
# I couldn't get the xclip subprocess to end properly running it from node.js!
# This is even though the stdin/stdout/stderr were all "end"-ed.
# I have no idea why it didn't work.  It works with other processes
# (even other X programs) as the subprocess progam.  It also works from python
# (and, here, shellscript) with xclip.  I tried setting "cwd" in the node.js
# spawn() options.  I tried exec() instead of spawn().
set -e
cd /home/danl/p/super_gen_pass
node simple_main.js "$@" | xclip
echo 'in clipboard'
